[workspace]
name = "aoc_2023"
version = "0.1.0"
description = "Advent of Code 2023 solutions in R"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
aoc = "Rscript main.R"

[target.osx.tasks]
rstudio = "open aoc_2023.Rproj"

[target.win.tasks]
rstudio = "start \"\" aoc_2023.Rproj"

[dependencies]
r-base = ">=4.5"
r-tidyverse = ">=2.0"

